### PR TITLE
Twitter small logos added

### PR DESCRIPTION
**Pull request by sumitbaroniya**
logo-added

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@sumitbaroniya I'd love to merge this but can u please update your branch?

**Comment by sumitbaroniya** [comment]
@Zack-Dx can you please tell me how to do this?
whether you mean branch name if it is then what should name i give?

**Comment by Zack-Dx** [comment]
> @Zack-Dx can you please tell me how to do this?

fetch it or sync your forked branch else make a new pr and paste ur changes there but make sure u copy ur changes else u'll lose it.

**Comment by sumitbaroniya** [comment]
I have created another PR please merge it

**Pull request closed without merging**
