### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Antonio-Bellini**
Style improvement to the UI

### CODE REVIEW

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-04 at 9 43 21 PM
Breaking Responsiveness.

**Comment by Antonio-Bellini** [comment]
Ah yes, because the UI changes don't consider the mobile view, but only the desktop view. I'll correct that.

**Comment by Zack-Dx** [comment]
> Ah yes, because the UI changes don't consider the mobile view, but only the desktop view. I'll correct that.

@Antonio-Bellini U'll do great. Just try removing that red border like thing and make it responsive for mobile/desktop/tabs.

**Comment by Antonio-Bellini** [comment]
On it. Thanks :)

**Pull request closed without merging**
