### PR TITLE
Color toggle

### LINKED ISSUE #4: Adding light and dark mode
Placing a toggle button to switch between light & dark mode.
@Zack-Dx  please assign me this under Hacktoberfest2022

### PR DESCRIPTION
**Pull request by Khushi-dev-1822**
Fixed #4  "Added toggle and fixed the overlapping issue"

### CODE REVIEW

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-04 at 11 05 48 PM
Khusi it's the same yet. Try using media queries over (1024px)

**Comment by Khushi-dev-1822** [comment]
I have used media queries, It was working fine

**Comment by Khushi-dev-1822** [comment]
screencapture-127-0-0-1-5500-HTML-index-html-2022-10-04-23_12_17

**Comment by Khushi-dev-1822** [comment]
Please check 2nd PR. There was everything I have fixed

**Comment by Khushi-dev-1822** [comment]
I am really sorry for closing this. Can you create a new issue regarding button media query

**Comment by Zack-Dx** [comment]
> I have used media queries, It was working fine


> I am really sorry for closing this. Can you create a new issue regarding button media query

you can create but I modified your style.css and now it's perfectly responsive for all.

**Pull request closed without merging**
