### PR TITLE
Khushi/signin button fix

### PR DESCRIPTION
**Pull request by Khushi-dev-1822**
I've fixed the overlapping issue.

### CODE REVIEW

**Comment by Zack-Dx** [comment]
> I've fixed the overlapping issue.

The time you closed the previous issue I modified your code and now it's responsive but you can do as per your credit.. just put index.html out of the folder and link images and css. It would help us to publish it in GitHub pages and then I'll merge it. Thanks!

**Comment by Khushi-dev-1822** [comment]
No, Thank you If you did that. I do really apologize for the conflicts that I've created.

**Comment by Zack-Dx** [comment]
> No, Thank you If you did that. I do really apologize for the conflicts that I've created.

So u wanna fix that Html thing?

**Comment by Khushi-dev-1822** [comment]
no

**Pull request closed without merging**
