### PR TITLE
Add Title and Categories in just like Twitter and remove irrelevant code.

### PR DESCRIPTION
**Pull request by AbdulRehmanGHub**
- Changed the Title Bar and add Title same as Twitter.
- More Categories to Website.
- Changed the Footer just like as Twitter official.
- Removed unwanted irrelevant lines of code.
Thanks.

### CODE REVIEW

**Comment by AbdulRehmanGHub** [comment]
Make the categories and footer just like the Twitter.

**Comment by Zack-Dx** [comment]
@AbdulRehmanGHub There's some kind of extra spacing below footer please check that else everything is perfect.

**Comment by AbdulRehmanGHub** [comment]
@Zack-Dx  Sir, check now please

**Comment by Zack-Dx** [comment]
@AbdulRehmanGHub Hi Abdul! u did a great work. Thank you for your contribution. Share love by giving a star to the repo. Merged!

**Pull request merged**
