### PR TITLE
height of container fixed

### PR DESCRIPTION
**Pull request by vardhan0604**
this is what it looks likes now...  I have made the the container 100vh as it should be and how it is in the org website 
 
PS- Add hacktoberfest label to this PR

image

### CODE REVIEW

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-04 at 10 12 25 PM
You did great! but your changes aren't being responsive with tablets try to fix that and it's ready to get merged.

**Comment by vardhan0604** [comment]
Okay I will look into it. Give me some time

**Comment by Zack-Dx** [comment]
> Okay I will look into it. Give me some time

@vardhan0604 Surely! take your time.

**Comment by vardhan0604** [comment]
hey, @Zack-Dx  I made it more responsive. I also fixed the issue of the height of the image on smaller screens

PS-pls add hacktoberfest label to the repo

image

**Comment by Zack-Dx** [comment]
> hey, @Zack-Dx I made it more responsive. I also fixed the issue of the height of the image on smaller screens
> 
> PS-pls add hacktoberfest label to the repo
> 
> image

@vardhan0604 Congratulations! loved this and merged! Make sure to star the repo Thank You!

**Comment by vardhan0604** [comment]
Yeah sure @Zack-Dx . 
Looking forward to making more contributions.

**Pull request merged**
