### PR TITLE
UI elements are aligned correctly

### PR DESCRIPTION
**Pull request by niteshjitender**
Twitter Landing Page issue
Twitter Landing Page Resolved

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@niteshjitender can u please pull out index.html and link it with assets else GitHub pages would go down.

**Comment by niteshjitender** [comment]
Hi @Zack-Dx 
There were no changes needed in the index.html I just have modified the css classes.

**Comment by Zack-Dx** [comment]
> Hi @Zack-Dx There were no changes needed in the index.html I just have modified the css classes.

If u don't put ur index.html out from the folder I can't publish it in  GitHub pages.

**Comment by niteshjitender** [comment]
I just added

> > Hi @Zack-Dx There were no changes needed in the index.html I just have modified the css classes.
> 
> If u don't put ur index.html out from the folder I can't publish it in GitHub pages.

I just updated my repo and now it has index.html.

**Comment by niteshjitender** [comment]
@Zack-Dx  It is not yet merged. I have done the required changes please look at this.

**Comment by Zack-Dx** [comment]
> @Zack-Dx It is not yet merged. I have done the required changes please look at this.

Github says your branch has conflicts please update with latest branch.

**Pull request closed without merging**
