### PR TITLE
Added responsive design

### LINKED ISSUE #7: Make responsive buttons in mobile view
The buttons are going outside the screen for mobile view
image

@Zack-Dx  Please assign this issue to me, I would love to make it better

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #7 

Updated view:
image

Adjusted buttons width on small screens

### CODE REVIEW

**Comment by Pranshu1902** [comment]
@Zack-Dx I have made a new PR which follows up on PR #8 . Please look into it and merge it, I resolved all the merge conflicts.

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-05 at 9 24 18 AM
Remove margin-left from this para. I'll merge this.

**Comment by Pranshu1902** [comment]
@Zack-Dx 
Updated view:
image

**Comment by Zack-Dx** [comment]
> @Zack-Dx Updated view: image

@Pranshu1902 Congrats! Amazing work. Thank you for your support.

**Pull request merged**
