### PR TITLE
first contribution

### PR DESCRIPTION
**Pull request by aakash1233333**
my first pull request

### CODE REVIEW

**Comment by Zack-Dx** [comment]
> my first pull request

@aakash1233333 best wishes from my side & make sure to star the repo.

**Comment by aakash1233333** [comment]
I want for Hacktoberfest

**Comment by Zack-Dx** [comment]
> I want for Hacktoberfest
> […](#)

@aakash1233333 already done!

**Comment by Antonio-Bellini** [comment]
Hey man, why you closed my pull request?

**Comment by aakash1233333** [comment]
What do you mean?

**Comment by Antonio-Bellini** [comment]
The owner closed both my PR because he said they were a page breaking but this because I made two PR (one for the html and one for the css) because I don't know how to add two files in a PR.

**Comment by aakash1233333** [comment]
Kindly approve my pull request it is showing waiting for approval for
Hacktoberfest
Thanks

**Comment by aakash1233333** [comment]
Please look into the matter it is showing in Hacktoberfest not merged

**Comment by Antonio-Bellini** [comment]
Hacktoberfest site says that the PR is in waiting (12 hours and 46 minutes
till the end)

Antonio

**Comment by aakash1233333** [comment]
Ok, thanks. Can I contribute in your project more ! Please assign me some
issues.

**Comment by aakash1233333** [comment]
I have contributed again please merged it .
Thanks

**Comment by aakash1233333** [comment]
I contributed again please merge it also

**Comment by aakash1233333** [comment]
I have contributed again please merge it
Thanks

**Comment by Antonio-Bellini** [comment]
What are you talking about?

Antonio

**Comment by aakash1233333** [comment]
What do you mean? I have contributed again on your project just check it !

**Comment by aakash1233333** [comment]
#92 my new PR
Thanks

**Comment by Antonio-Bellini** [comment]
Man I have no project for the Hacktoberfest.

**Comment by aakash1233333** [comment]
Please merge my another contribution! Which I have made #92 PR
Thanks

**Comment by Antonio-Bellini** [comment]
MAN, it's simple.
I haven't any repository for Hacktoberfest.
That one where you have contributed is a for of the original of Zack-Dx

Il giorno lun 17 ott 2022 alle ore 19:59 AAKASH GANDHI <
***@***.***> ha scritto:

> Please merge my another contribution! Which I have made #92 PR
> Thanks
>

**Comment by Antonio-Bellini** [comment]
You have to PR Zack-Dx

Il giorno lun 17 ott 2022 alle ore 20:04 Antonio Bellini <
***@***.***> ha scritto:

> MAN, it's simple.
> I haven't any repository for Hacktoberfest.
> That one where you have contributed is a for of the original of Zack-Dx
>
> Il giorno lun 17 ott 2022 alle ore 19:59 AAKASH GANDHI <
> ***@***.***> ha scritto:
>
>> Please merge my another contribution! Which I have made #92 PR
>> Thanks
>>

**Comment by aakash1233333** [comment]
Please see my PR

**Comment by aakash1233333** [comment]
Please merge my another contribution!
PR #92
Thanks

**Comment by aakash1233333** [comment]
Please merge my another PR

**Comment by Antonio-Bellini** [comment]
[image: image.png]
I HAVE NO PULL REQUEST, BECAUSE I'M NOT THE OWNER OF THIS REPO

Il giorno lun 17 ott 2022 alle ore 20:12 AAKASH GANDHI <
***@***.***> ha scritto:

> Please merge my another PR
>

**Comment by aakash1233333** [comment]
Done. Please give him mail id because i think by mistake you are receiving
because you are present in the the CC of my mail .

**Comment by aakash1233333** [comment]
Please see my PR #92 contributed again and merge it.

**Pull request merged**
