### PR TITLE
added color toggle functionality

### LINKED ISSUE #4: Adding light and dark mode
Placing a toggle button to switch between light & dark mode.
@Zack-Dx  please assign me this under Hacktoberfest2022

### PR DESCRIPTION
**Pull request by Khushi-dev-1822**
Fixed #4 "Adding light and dark mode".  [Adding light and dark mode](https://github.com/Zack-Dx/Twitter-Landing-Page/issues/4)

### CODE REVIEW

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-04 at 10 20 29 PM
It's amazing I'd love to merge this one. Just try to position this Sign in for desktop and get merged.

**Comment by Khushi-dev-1822** [comment]
Are you talking about btn's responsiveness??

**Comment by Khushi-dev-1822** [comment]
or should I center that button?

**Comment by Zack-Dx** [comment]
> or should I center that button?

it's overlapping with the footer just fix that!

**Comment by Khushi-dev-1822** [comment]
Okay, I'll do that. Can you do me a favor?  There is an issue regarding UI fixing I'll work on that one and I'll fix everything. Can you just merge this one If you don't mind

**Comment by Zack-Dx** [comment]
> Okay, I'll do that. Can you do me a favor? There is an issue regarding UI fixing I'll work on that one and I'll fix everything. Can you just merge this one If you don't mind

Sure! try to raise an issue regarding this and make sure to give repo a star. Thank You for the feature.

**Comment by Khushi-dev-1822** [comment]
Hey, I just pushed the changes

**Comment by Khushi-dev-1822** [comment]
Should I create another PR ??

**Comment by Zack-Dx** [comment]
> 

@Khushi-dev-1822 Ya sure.

**Comment by Khushi-dev-1822** [comment]
I have fixed the overlapping issue and pushed it to the previous PR that you closed. 
So should I make another PR ??

**Comment by Zack-Dx** [comment]
> I have fixed the overlapping issue and pushed it to the previous PR that you closed. So should I make another PR ??

Yes. You need to!

**Comment by Khushi-dev-1822** [comment]
Okay I'll do that now

**Comment by Zack-Dx** [comment]
> Okay I'll do that now

ha!

**Comment by Khushi-dev-1822** [comment]
Can you check? I have create a pull request

**Comment by Khushi-dev-1822** [comment]
And please give me hacktoberfest label if you really like my work

**Comment by Zack-Dx** [comment]
> And please give me hacktoberfest label if you really like my work

Already labelled hai.

**Comment by Khushi-dev-1822** [comment]
Thank you so much :)

**Pull request merged**
