### PR TITLE
favicon added

### PR DESCRIPTION
**Pull request by trisha-thakur**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@trisha-thakur use fav-icon generator to add fav icons else it'll not be responsive.

**Comment by trisha-thakur** [comment]
okay on it

**Comment by trisha-thakur** [comment]
i have made the changes please check

**Comment by Zack-Dx** [comment]
> i have made the changes please check

your branch has conflicting files please update with the latest one and create a new pull request. Thank YOU!

**Pull request closed without merging**
