### PR TITLE
Added responsiveness on buttons in mobile view

### LINKED ISSUE #7: Make responsive buttons in mobile view
The buttons are going outside the screen for mobile view
image

@Zack-Dx  Please assign this issue to me, I would love to make it better

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #7 

The buttons shrink based on the screen size.
image

### CODE REVIEW

**Comment by Pranshu1902** [comment]
@Zack-Dx please check and verify if any other changes are required.

**Comment by Zack-Dx** [comment]
> @Zack-Dx please check and verify if any other changes are required.

@Pranshu1902 fix the reponsiveness it's breaking!

**Comment by Pranshu1902** [comment]
> > @Zack-Dx please check and verify if any other changes are required.
> 
> @Pranshu1902 fix the reponsiveness it's breaking!

Ok, on it

**Comment by Pranshu1902** [comment]
@Zack-Dx 
Updated view:
image

Could you please specify if anything else is not responsive, I made the `Sign in` button response as well

**Review by Zack-Dx — CHANGES_REQUESTED** [review]
Screenshot 2022-10-04 at 6 18 58 PM
Overlapping Footer ( just try fixing the height)

**Comment by Pranshu1902** [comment]
@Zack-Dx 
Done!
image

**Comment by Zack-Dx** [comment]
Brother, your branch isn't updated with the latest one so I'm unable to merge it. Please update it first!

**Pull request closed without merging**
